### ISSUE TITLE
How to build with debug symbols?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [AutonomyLab/ardronelib#7]
Sorry for such a trivial question, but I just can't figure out where in the makefile to set the debug flag.
I'm working on Ubuntu 14.04.2.

**Figured it out.**

In "ARDroneLib/Soft/Build/config.makefile" Need to change "RELEASE_BUILD = yes" to "RELEASE_BUILD = no"

Cheers,
Nap

**Comment by mani-monaj** [comment]
Thanks. It might actually not be so trivial for people who need this. I will add this to the documentation.
